/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TeamAgentIdRouteImport } from './routes/team.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAgentIdRoute = TeamAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => TeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/board'
    | '/chat'
    | '/goals'
    | '/knowledge'
    | '/pipelines'
    | '/resources'
    | '/settings'
    | '/team'
    | '/runs/$runId'
    | '/tasks/$taskId'
    | '/team/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/board'
    | '/chat'
    | '/goals'
    | '/knowledge'
    | '/pipelines'
    | '/resources'
    | '/settings'
    | '/team'
    | '/runs/$runId'
    | '/tasks/$taskId'
    | '/team/$agentId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/board'
    | '/chat'
    | '/goals'
    | '/knowledge'
    | '/pipelines'
    | '/resources'
    | '/settings'
    | '/team'
    | '/runs/$runId'
    | '/tasks/$taskId'
    | '/team/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BoardRoute: typeof BoardRoute
  ChatRoute: typeof ChatRoute
  GoalsRoute: typeof GoalsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PipelinesRoute: typeof PipelinesRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRouteWithChildren
  RunsRunIdRoute: typeof RunsRunIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$agentId': {
      id: '/team/$agentId'
      path: '/$agentId'
      fullPath: '/team/$agentId'
      preLoaderRoute: typeof TeamAgentIdRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface TeamRouteChildren {
  TeamAgentIdRoute: typeof TeamAgentIdRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamAgentIdRoute: TeamAgentIdRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BoardRoute: BoardRoute,
  ChatRoute: ChatRoute,
  GoalsRoute: GoalsRoute,
  KnowledgeRoute: KnowledgeRoute,
  PipelinesRoute: PipelinesRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRouteWithChildren,
  RunsRunIdRoute: RunsRunIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
