#!/usr/bin/env bash

set -euo pipefail
umask 077

readonly SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=lib/dev.sh
source "$SCRIPT_DIR/lib/dev.sh"

random_hex() {
    od -An -N24 -tx1 /dev/urandom | tr -d ' \n'
}

has_assignment() {
    local file="$1"
    local key="$2"

    grep -q "^${key}=" "$file"
}

ensure_assignment() {
    local file="$1"
    local key="$2"
    local value="$3"

    if ! has_assignment "$file" "$key"; then
        printf '%s=%s\n' "$key" "$value" >>"$file"
    fi
}

source_existing_environment() {
    set -a
    # The files were generated by Forge with shell-safe values and are owner-only.
    # shellcheck disable=SC1090
    source "$FORGE_DEV_CONFIG_FILE"
    # shellcheck disable=SC1090
    source "$FORGE_DEV_SECRETS_FILE"
    set +a
}

ensure_extended_configuration() {
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_REDIS_HOST 127.0.0.1
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_REDIS_PORT 56379
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_MINIO_HOST 127.0.0.1
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_MINIO_PORT 59000
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_MINIO_CONSOLE_PORT 59001
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_MINIO_ROOT_USER forge
    ensure_assignment "$FORGE_DEV_CONFIG_FILE" FORGE_MINIO_TEST_BUCKET_PREFIX forge-it

    source_existing_environment
    ensure_assignment "$FORGE_DEV_SECRETS_FILE" FORGE_REDIS_PASSWORD "$(random_hex)"
    ensure_assignment "$FORGE_DEV_SECRETS_FILE" FORGE_MINIO_ROOT_PASSWORD "$(random_hex)"
    source_existing_environment
    ensure_assignment "$FORGE_DEV_SECRETS_FILE" FORGE_REDIS_URL \
        "redis://:${FORGE_REDIS_PASSWORD}@${FORGE_REDIS_HOST}:${FORGE_REDIS_PORT}/0"
    ensure_assignment "$FORGE_DEV_SECRETS_FILE" FORGE_MINIO_ENDPOINT \
        "http://${FORGE_MINIO_HOST}:${FORGE_MINIO_PORT}"
}

require_command podman
require_command podman-compose
require_rootless_podman

mkdir -p "$FORGE_DEV_DIR"
chmod 700 "$FORGE_DEV_DIR"

if [[ -e "$FORGE_DEV_CONFIG_FILE" || -e "$FORGE_DEV_SECRETS_FILE" ]]; then
    [[ -f "$FORGE_DEV_CONFIG_FILE" && -f "$FORGE_DEV_SECRETS_FILE" ]] || \
        fail "development configuration is incomplete; repair it manually before retrying"
    [[ ! -L "$FORGE_DEV_CONFIG_FILE" && ! -L "$FORGE_DEV_SECRETS_FILE" ]] || \
        fail "refusing symlinked development configuration"
    chmod 600 "$FORGE_DEV_CONFIG_FILE" "$FORGE_DEV_SECRETS_FILE"
    ensure_extended_configuration
    chmod 600 "$FORGE_DEV_CONFIG_FILE" "$FORGE_DEV_SECRETS_FILE"
    printf 'Forge development configuration is ready in %s\n' "$FORGE_DEV_DIR"
    exit 0
fi

postgres_password="$(random_hex)"
nats_auth_token="$(random_hex)"
redis_password="$(random_hex)"
minio_root_password="$(random_hex)"

{
    printf '%s\n' 'FORGE_COMPOSE_PROJECT_NAME=forge-m0'
    printf '%s\n' 'FORGE_POSTGRES_DATABASE=forge'
    printf '%s\n' 'FORGE_POSTGRES_USER=forge'
    printf '%s\n' 'FORGE_POSTGRES_HOST=127.0.0.1'
    printf '%s\n' 'FORGE_POSTGRES_PORT=55432'
    printf '%s\n' 'FORGE_NATS_HOST=127.0.0.1'
    printf '%s\n' 'FORGE_NATS_PORT=54222'
    printf '%s\n' 'FORGE_NATS_MONITOR_PORT=58222'
    printf '%s\n' 'FORGE_REDIS_HOST=127.0.0.1'
    printf '%s\n' 'FORGE_REDIS_PORT=56379'
    printf '%s\n' 'FORGE_MINIO_HOST=127.0.0.1'
    printf '%s\n' 'FORGE_MINIO_PORT=59000'
    printf '%s\n' 'FORGE_MINIO_CONSOLE_PORT=59001'
    printf '%s\n' 'FORGE_MINIO_ROOT_USER=forge'
    printf '%s\n' 'FORGE_MINIO_TEST_BUCKET_PREFIX=forge-it'
} >"$FORGE_DEV_CONFIG_FILE"

{
    printf 'FORGE_POSTGRES_PASSWORD=%s\n' "$postgres_password"
    printf 'FORGE_NATS_AUTH_TOKEN=%s\n' "$nats_auth_token"
    printf 'FORGE_REDIS_PASSWORD=%s\n' "$redis_password"
    printf 'FORGE_MINIO_ROOT_PASSWORD=%s\n' "$minio_root_password"
    printf 'FORGE_DATABASE_URL=postgresql://forge:%s@127.0.0.1:55432/forge\n' "$postgres_password"
    printf 'FORGE_NATS_URL=nats://%s@127.0.0.1:54222\n' "$nats_auth_token"
    printf 'FORGE_REDIS_URL=redis://:%s@127.0.0.1:56379/0\n' "$redis_password"
    printf '%s\n' 'FORGE_MINIO_ENDPOINT=http://127.0.0.1:59000'
} >"$FORGE_DEV_SECRETS_FILE"

chmod 600 "$FORGE_DEV_CONFIG_FILE" "$FORGE_DEV_SECRETS_FILE"
printf 'Created owner-only Forge development configuration in %s\n' "$FORGE_DEV_DIR"
